//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplinaryReport.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRHearing
    {
        public string DR_HEAR_CHIEF_ID { get; set; }
        public string DRInvestigationDR_INVEST_EMP_ID { get; set; }
        public int DRInvestigationDRDR_REPORT_NUM { get; set; }
        public string DRInvestigationDRDR_FIRST_APPROVAL_EMP_ID { get; set; }
        public string DRInvestigationDREmployeeEMP_ID { get; set; }
        public string DR_HEAR_INM_PLEA { get; set; }
        public string DR_HEAR_WIT_REQ { get; set; }
        public string DR_HEAR_NO_REAPORTS { get; set; }
        public System.DateTime DR_HEAR_DATE { get; set; }
        public string DR_HEAR_DEC { get; set; }
        public string DR_HEAR_APPEAL { get; set; }
        public string DR_HEAR_DAYS_DSC_CONF { get; set; }
        public string DR_HEAR_WKS_LOSS_COMMIS { get; set; }
        public string DR_HEAR_DAYS_LOSS_GAINTIME { get; set; }
        public string DR_HEAR_REV_TENT_DEL_DATE { get; set; }
        public string DR_HEAR_COMMENT { get; set; }
        public string DR_HEAR_INM_INSTRULES_ACK { get; set; }
        public string DR_HEAR_COM_CHAIR_ID { get; set; }
        public string DR_HEAR_INM_WIT_ID { get; set; }
        public string DR_HEAR_CHIEF_AGREE_FLAG { get; set; }
        public string DR_HEAR_CHIEF_REDUCE_FLAG { get; set; }
    
        public virtual DRInvestigation DRInvestigation { get; set; }
    }
}
