//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplinaryReport.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRInvestigation
    {
        public DRInvestigation()
        {
            this.DRHearings = new HashSet<DRHearing>();
        }
    
        public string DR_INVEST_EMP_ID { get; set; }
        public int DisciplinaryReportDR_REPORT_NUM { get; set; }
        public string DisciplinaryReportDR_FIRST_APPROVAL_EMP_ID { get; set; }
        public string DisciplinaryReportEmployeeEMP_ID { get; set; }
        public System.DateTime DR_INVEST_DATE { get; set; }
        public string DR_DATE_INVEST_COMP { get; set; }
        public string DR_TIME_INVEST_COMP { get; set; }
        public string DR_INVEST_STATEMENT { get; set; }
        public string DR_INVEST_COMP_FLAG { get; set; }
        public string DR_INVEST_VOID { get; set; }
        public string DR_INVEST_APPROVE { get; set; }
        public string DR_INVEST_REJECT { get; set; }
        public string DR_INVEST_REJ_REASON { get; set; }
        public string DR_INVEST_SUP_VOID { get; set; }
    
        public virtual DR DisciplinaryReport { get; set; }
        public virtual ICollection<DRHearing> DRHearings { get; set; }
    }
}
