//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplinaryReport.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DisciplinaryReports = new HashSet<DR>();
        }
    
        public string EMP_ID { get; set; }
        public string EMP_PASSW { get; set; }
        public string EMP_LAST_NAME { get; set; }
        public string EMP_FIRST_NAME { get; set; }
        public string EMP_ROLE { get; set; }
        public string EMP_LOCATION { get; set; }
    
        public virtual ICollection<DR> DisciplinaryReports { get; set; }
    }
}
