//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplinaryReport.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.DisciplinaryReports = new HashSet<DR>();
        }
    
        public string LOC_FAC_CODE { get; set; }
        public string LOC_FAC_DESC { get; set; }
        public string LOC_CODE { get; set; }
        public string LOC_DESC { get; set; }
    
        public virtual ICollection<DR> DisciplinaryReports { get; set; }
    }
}
