//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplinaryReport.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        public Violation()
        {
            this.DisciplinaryReports = new HashSet<DR>();
        }
    
        public string VIO_CODE { get; set; }
        public string VIO_SHORT_DESC { get; set; }
        public string VIO_LONG_DESC { get; set; }
        public string VIO_R_FLAG { get; set; }
    
        public virtual ICollection<DR> DisciplinaryReports { get; set; }
    }
}
