//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRApplication
{
    using DRApplication.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class JSO : DbContext
    {
        public JSO()
            : base("name=JSO")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<DR> DRs { get; set; }
        public DbSet<DRHEARING> DRHEARINGs { get; set; }
        public DbSet<DRINVESTIGATION> DRINVESTIGATIONs { get; set; }
        public DbSet<DRTEMP> DRTEMPs { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public DbSet<HOUSINGLOCATION> HOUSINGLOCATIONs { get; set; }
        public DbSet<INCIDENTLOCATION> INCIDENTLOCATIONs { get; set; }
        public DbSet<LOCATION> LOCATIONs { get; set; }
        public DbSet<VIOLATION> VIOLATIONs { get; set; }
    }
}
